
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.1.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Skipping commits affecting specific files (GitHub only).
# More details here: /docs/appveyor-yml
skip_commits:
  files:
    - misc/*
    - sandbox/*
    - docs/*
    - '**/*.md'
    - '**/.gitattributes'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Ubuntu2204

install:
  - sudo apt update && sudo apt install -y dotnet-sdk-8.0

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  - ./build.sh

# AppVeyor's Tests Window is empty?
# See https://stackoverflow.com/a/53309039/818321
test_script:
  - nuget install Appveyor.TestLogger -Version 2.0.0 -Source https://api.nuget.org/v3/index.json
  - dotnet test --no-build --no-restore --test-adapter-path:. --logger:Appveyor ./src/Tests/Tests.fsproj
