EYE_CATCH        = -1

#
# Tags
#

UNIT_TAG         = 1
INT_TAG          = 2
STRING_TAG       = 3
BOOLEAN_TAG      = 4
ARRAYANY_TAG     = 5
IO_TAG           = 6

#
# Offsets
#

OBJ_EYE_CATCH    = -8

OBJ_TAG          = 0
OBJ_SIZE         = 8
OBJ_VTAB         = 16
OBJ_ATTR         = 24

STR_LEN          = 24
STR_VAL          = 32

ARR_LEN          = 24
ARR_ITEMS        = 32

BOOL_VAL         = 24

INT_VAL          = 24
